# CONFIGMAP EXAMPLE - Frontend Serviços Públicos

apiVersion: v1
kind: ConfigMap
metadata:
  name: servicos-front-env
  labels:
    io.kompose.service: servicos-front-publicos

data:
  # AMBIENTE
  NODE_ENV: "production"
  
  # API URLs
  # Server-side (chamadas do Next.js server - interno no cluster)
  API_URL_SERVER_SIDED: "http://servicospublicos-api:80"
  
  # Client-side (chamadas do navegador - URL pública)
  NEXT_PUBLIC_API_URL: "https://servicospublicos-api.app.fslab.dev"
  
  # NEXTAUTH
  NEXTAUTH_URL: "https://servicospublicos.app.fslab.dev"
  
  # GERAR: openssl rand -base64 48
  NEXTAUTH_SECRET: "<GERAR_COM_OPENSSL>"
  
  # Proxy OAuth Callback
  PROXY_OAUTH_CALLBACK: "true"
